/*

 EXPORT.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0xFF,0x81,0x81,0xE7,0xE7,0x81,0xA5,
  0x42,0x42,0x5A,0x42,0x3C,0x3C,0x00,0x00,
  0xFF,0xFF,0x81,0x81,0xE7,0xE7,0x81,0xA5,
  0x42,0x42,0x42,0x42,0x3C,0x3C,0x00,0x00
};

/* End of EXPORT.C */
